name: Сборка и публикация Jupyter Book (ручной запуск)

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout репозитория
      uses: actions/checkout@v4
    
    - name: Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Установка зависимостей
      run: |
        pip install --upgrade pip
        pip install jupyter-book
        pip install -r requirements.txt
    
    - name: Сборка книги
      run: |
        export GUIDE_RANDOM_SEED=4920385
        jupyter-book build --all .
    
    - name: Публикация на GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        destination_dir: manual-deploy
